development:
  admin_name: 'arjun_verma'
  admin_email: 'arjun@aceteksolutions.com'
  admin_password: 'admin'
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: twitter_data_analytics
  secret_key_base: 0dbe7cdea3c1ea99e5b8d47e870e95de1fd3fe3805b489f47d6b1382d896eca04790c9d5e5be8e448a326ee81e0cfa865b3a9bc6f3761614ba628e418198a37d
  site_title: Twitter Data Analytics
  site_description: Performing NLP on Twitter data
production:
  admin_name: 'arjun_verma'
  admin_email: 'arjun@aceteksolutions.com'
  admin_password: 'admin'
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: twitter_data_analytics
  secret_key_base: 0dbe7cdea3c1ea99e5b8d47e870e95de1fd3fe3805b489f47d6b1382d896eca04790c9d5e5be8e448a326ee81e0cfa865b3a9bc6f3761614ba628e418198a37d
  site_title: Twitter Data Analytics
  site_description: Performing NLP on Twitter data

